### ISSUE TITLE
在pc用模拟器启动时报crash

### ISSUE THREAD

**Issue by hugebug4ever** [cocos-creator/tutorial-hot-update#1]
cocos creator 1.1
打开项目， 选择模拟器启动游戏。
出下下面这个报错
![error](https://cloud.githubusercontent.com/assets/846278/16027695/aa89323e-320a-11e6-8455-25b988f8386f.png)

**Comment by xianyinchen** [comment]
你好，模拟器不支持测试热更新，请构建app测试，如果是非热更新问题，请提到engine-native仓库。
