### ISSUE TITLE
安卓更新完毕重启，检查更新发现还是有更新。

### ISSUE THREAD

**Issue by 845629143** [cocos-creator/tutorial-hot-update#3]
更新完成重新启动，点击检查更新按钮，发现还是可以找到更新版本。
再三确认提示更新完成，而不是更新失败。

查看设备内数据，发现storagePath目录下面没有任何东西。
var storagePath = ((jsb.fileUtils ? jsb.fileUtils.getWritablePath() : '/') + 'blackjack-remote-asset');
console.log('Storage path for remote asset : ' + storagePath);
但是在storagePath_temp目录下面有一个version文件。

logcat日志
http://url.cn/45RIvYP

creator版本1.4
开发环境windows
安卓机型 小米

**Comment by wuhenLin** [comment]
热更完成后，temp目录下的文件是需要删除，并把文件移动到storage path中，然后把文件的temp后缀名去除掉，删除temp目录，再重启,查看下下载文件是否有错误，示例中最大下载错误允许5个文件


------------------ 原始邮件 ------------------
发件人: "845629143";<notifications@github.com>;
发送时间: 2017年2月27日(星期一) 晚上7:56
收件人: "cocos-creator/tutorial-hot-update"<tutorial-hot-update@noreply.github.com>; 
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: [cocos-creator/tutorial-hot-update] 安卓更新完毕重启，检查更新发现还是有更新。 (#3)




更新完成重新启动，点击检查更新按钮，发现还是可以找到更新版本。
 再三确认提示更新完成，而不是更新失败。
 
查看设备内数据，发现storagePath目录下面没有任何东西。
 var storagePath = ((jsb.fileUtils ? jsb.fileUtils.getWritablePath() : '/') + 'blackjack-remote-asset');
 console.log('Storage path for remote asset : ' + storagePath);
 但是在storagePath_temp目录下面有一个version文件。
 
logcat日志
 http://url.cn/45RIvYP
 
creator版本1.4
 开发环境windows
 安卓机型 小米
