### ISSUE TITLE
大版本更新问题

### ISSUE THREAD

**Issue by DeloDuan** [cocos-creator/tutorial-hot-update#7]
如果遇到大版本更新，比如apk重新更新，如何重置缓存更新目录？ 可以用 cc.sys.osVersion 和 cc.sys.osMainVersion 来控制吧？那是不是必须得在main.js里面添加控制逻辑

**Comment by jareguo** [comment]
大版本更新通常需要重新下载 apk 才行。程序自己生成的缓存需要用户自行进行版本控制喔。
